
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KnjiznicaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Knjiznica
{

    public Knjiznica()
    {

        this.ClanKnjiznices = new HashSet<ClanKnjiznice>();

        this.Knjigas = new HashSet<Knjiga>();

        this.Posudbas = new HashSet<Posudba>();

        this.Zaposleniks = new HashSet<Zaposlenik>();

    }


    public int ID { get; set; }

    public string NazivKnjiznice { get; set; }

    public string AdresaKnjiznice { get; set; }



    public virtual ICollection<ClanKnjiznice> ClanKnjiznices { get; set; }

    public virtual ICollection<Knjiga> Knjigas { get; set; }

    public virtual ICollection<Posudba> Posudbas { get; set; }

    public virtual ICollection<Zaposlenik> Zaposleniks { get; set; }

}

}
