

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KnjiznicaAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBKnjiznicaEntities : DbContext
{
    public DBKnjiznicaEntities()
        : base("name=DBKnjiznicaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<ClanKnjiznice> ClanKnjiznices { get; set; }

    public DbSet<Knjiga> Knjigas { get; set; }

    public DbSet<Knjiznica> Knjiznicas { get; set; }

    public DbSet<Posudba> Posudbas { get; set; }

    public DbSet<Zaposlenik> Zaposleniks { get; set; }

}

}

