
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KnjiznicaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Posudba
{

    public int ID { get; set; }

    public int KnjiznicaID { get; set; }

    public int KnjigaID { get; set; }

    public int ClanID { get; set; }

    public int ZaposlenikID { get; set; }

    public System.DateTime DatumPreuzimanja { get; set; }

    public Nullable<System.DateTime> DatumVracanja { get; set; }



    public virtual ClanKnjiznice ClanKnjiznice { get; set; }

    public virtual Knjiga Knjiga { get; set; }

    public virtual Knjiznica Knjiznica { get; set; }

    public virtual Zaposlenik Zaposlenik { get; set; }

}

}
